version: '3'

networks:
    nginx-php74-mariadb-node:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php74-service
            - mariadb-service
        networks:
            - nginx-php74-mariadb-node

    # php
    php74-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php74-container
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/project
        networks:
            - nginx-php74-mariadb-node

    # mariadb
    mariadb-service:
        image: mariadb
        container_name: mariadb_container
        volumes:
            - ./mysql:/var/lib/mysql
        restart: unless-stopped
        environment:
            MARIADB_ROOT_PASSWORD: admin
            MARIADB_PASSWORD: admin
            MARIADB_USER: admin
            MARIADB_MYSQL_LOCALHOST_USER: admin
            MARIADB_DATABASE: test
        networks:
            - nginx-php74-mariadb-node

    # node
    node-service:
        image: node:latest
        container_name: node-container
        volumes:
            - ./app:/var/www/project
        working_dir: /var/www/project
        networks:
            - nginx-php74-mariadb-node